import { contextBridge, ipcRenderer } from 'electron'
import type { BranchPilotApi } from '../src/shared/branchPilot.js'
import type { BranchPilotIpcChannel } from '../src/shared/ipcChannels.js'

const invoke = <T,>(channel: BranchPilotIpcChannel, ...args: unknown[]) => ipcRenderer.invoke(channel, ...args) as Promise<T>

const branchPilot: BranchPilotApi = {
  onMenuAction: (callback) => {
    const listener = (_event: unknown, action: string) => callback(action)
    ipcRenderer.on('menu:action', listener)
    return () => ipcRenderer.removeListener('menu:action', listener)
  },
  getVersion: () => invoke('app:version'),
  chooseAndOpenRepository: () => invoke('repository:chooseAndOpen'),
  cloneRepository: (request) => invoke('repository:clone', request),
  openRepository: (path) => invoke('repository:open', path),
  getRecentRepositories: () => invoke('repository:recent'),
  setRepositoryPinned: (request) => invoke('repository:setPinned', request),
  getRepositoryDashboard: (repoPath) => invoke('repository:dashboard', repoPath),
  refreshRepository: (repoPath) => invoke('repository:refresh', repoPath),
  getDiff: (request) => invoke('repository:diff', request),
  getImagePreview: (request) => invoke('repository:imagePreview', request),
  getContributionGraph: (repoPath) => invoke('repository:contributionGraph', repoPath),
  getContributors: (repoPath) => invoke('repository:contributors', repoPath),
  getGitHubContributors: (repoPath) => invoke('providers:githubContributors', repoPath),
  getHistory: (repoPath) => invoke('repository:history', repoPath),
  getCommitDetails: (request) => invoke('repository:commitDetails', request),
  getCommitFileDiff: (request) => invoke('repository:commitFileDiff', request),
  getProjectMemory: (repoPath) => invoke('repository:projectMemory', repoPath),
  getProjectWiki: (repoPath) => invoke('repository:projectWiki', repoPath),
  scanProjectMemory: (repoPath) => invoke('repository:scanProjectMemory', repoPath),
  generateProjectWiki: (repoPath) => invoke('repository:generateProjectWiki', repoPath),
  getProjectMemoryMcpConfig: (repoPath) => invoke('repository:projectMemoryMcpConfig', repoPath),
  getAssistantPolicy: (repoPath) => invoke('assistants:getPolicy', repoPath),
  setAssistantPolicy: (update) => invoke('assistants:setPolicy', update),
  getEditorSettings: () => invoke('editor:getSettings'),
  setEditorSettings: (update) => invoke('editor:setSettings', update),
  getActivityLog: (query) => invoke('activity:list', query),
  clearActivityLog: (repoPath, confirmed) => invoke('activity:clear', repoPath, confirmed),
  generateDailyReview: (request) => invoke('daily:generate', request),
  getGitConfig: (repoPath) => invoke('repository:gitConfig', repoPath),
  setLocalGitIdentity: (request) => invoke('repository:setLocalGitIdentity', request),
  addRemote: (request) => invoke('git:addRemote', request),
  setRemoteUrl: (request) => invoke('git:setRemoteUrl', request),
  removeRemote: (request) => invoke('git:removeRemote', request),
  stageFile: (request) => invoke('git:stageFile', request),
  unstageFile: (request) => invoke('git:unstageFile', request),
  stageHunk: (request) => invoke('git:stageHunk', request),
  unstageHunk: (request) => invoke('git:unstageHunk', request),
  stageAll: (repoPath) => invoke('git:stageAll', repoPath),
  unstageAll: (repoPath) => invoke('git:unstageAll', repoPath),
  discardFile: (request) => invoke('git:discardFile', request),
  deleteUntrackedFile: (request) => invoke('git:deleteUntrackedFile', request),
  commit: (request) => invoke('git:commit', request),
  amendCommit: (request) => invoke('git:amendCommit', request),
  revertCommit: (request) => invoke('git:revertCommit', request),
  cherryPickCommit: (request) => invoke('git:cherryPickCommit', request),
  listStashes: (repoPath) => invoke('stash:list', repoPath),
  createStash: (request) => invoke('stash:create', request),
  applyStash: (request) => invoke('stash:apply', request),
  dropStash: (request) => invoke('stash:drop', request),
  fetch: (repoPath) => invoke('git:fetch', repoPath),
  pull: (repoPath) => invoke('git:pull', repoPath),
  push: (repoPath) => invoke('git:push', repoPath),
  publishBranch: (request) => invoke('git:publishBranch', request),
  createBranch: (request) => invoke('git:createBranch', request),
  renameBranch: (request) => invoke('git:renameBranch', request),
  setBranchUpstream: (request) => invoke('git:setBranchUpstream', request),
  updateBranchDescription: (request) => invoke('git:updateBranchDescription', request),
  compareBranch: (request) => invoke('git:compareBranch', request),
  switchBranch: (request) => invoke('git:switchBranch', request),
  deleteBranch: (request) => invoke('git:deleteBranch', request),
  createTag: (request) => invoke('git:createTag', request),
  deleteTag: (request) => invoke('git:deleteTag', request),
  listWorktrees: (repoPath) => invoke('git:listWorktrees', repoPath),
  createWorktree: (request) => invoke('git:createWorktree', request),
  removeWorktree: (request) => invoke('git:removeWorktree', request),
  listSubmodules: (repoPath) => invoke('git:listSubmodules', repoPath),
  updateSubmodule: (request) => invoke('git:updateSubmodule', request),
  getGitLfsSummary: (repoPath) => invoke('git:lfsSummary', repoPath),
  pullGitLfs: (repoPath) => invoke('git:lfsPull', repoPath),
  exportPatch: (request) => invoke('git:exportPatch', request),
  applyPatch: (request) => invoke('git:applyPatch', request),
  acceptOurs: (request) => invoke('merge:acceptOurs', request),
  acceptTheirs: (request) => invoke('merge:acceptTheirs', request),
  markResolved: (request) => invoke('merge:markResolved', request),
  mergeBranch: (request) => invoke('merge:start', request),
  rebaseBranch: (request) => invoke('rebase:start', request),
  continueMergeOperation: (repoPath) => invoke('merge:continue', repoPath),
  abortMergeOperation: (repoPath) => invoke('merge:abort', repoPath),
  openInEditor: (request) => invoke('editor:open', request),
  openTerminal: (targetPath) => invoke('terminal:open', targetPath),
  listProviders: () => invoke('providers:list'),
  listAssistants: () => invoke('assistants:list'),
  checkAssistants: () => invoke('assistants:check'),
  generateCommitMessage: (request) => invoke('assistants:generateCommitMessage', request),
  generateBranchDraft: (request) => invoke('assistants:generateBranchDraft', request),
  generateBranchDescription: (request) => invoke('assistants:generateBranchDescription', request),
  generateLinkedInProject: (request) => invoke('assistants:generateLinkedInProject', request),
  getGitHubCliStatus: (repoPath) => invoke('providers:githubCliStatus', repoPath),
  generatePullRequestText: (request) => invoke('assistants:generatePullRequestText', request),
  createGitHubPullRequest: (request) => invoke('providers:createGitHubPullRequest', request),
  getCurrentBranchPullRequest: (repoPath) => invoke('providers:currentGitHubPullRequest', repoPath),
  listGitHubPullRequests: (repoPath) => invoke('providers:listGitHubPullRequests', repoPath),
  listGitHubAccounts: () => invoke('providers:listGitHubAccounts'),
  listGitHubRepositories: (request) => invoke('providers:listGitHubRepositories', request),
  getGitHubPullRequestDetails: (request) => invoke('providers:getGitHubPullRequestDetails', request),
  getGitHubPullRequestChecks: (request) => invoke('providers:getGitHubPullRequestChecks', request),
  getGitHubPullRequestDiff: (request) => invoke('providers:getGitHubPullRequestDiff', request),
  checkoutGitHubPullRequest: (request) => invoke('providers:checkoutGitHubPullRequest', request),
  generateReviewReport: (request) => invoke('assistants:generateReviewReport', request)
}

window.addEventListener('DOMContentLoaded', () => {
  document.documentElement.dataset.platform = process.platform
})

contextBridge.exposeInMainWorld('branchPilot', branchPilot)
