import { contextBridge, ipcRenderer } from 'electron'
import type { BranchPilotApi } from '../src/shared/branchPilot.js'

const invoke = <T>(channel: string, ...args: unknown[]) => ipcRenderer.invoke(channel, ...args) as Promise<T>

const branchPilot: BranchPilotApi = {
  getVersion: () => invoke('app:version'),
  chooseAndOpenRepository: () => invoke('repository:chooseAndOpen'),
  openRepository: (path) => invoke('repository:open', path),
  getRecentRepositories: () => invoke('repository:recent'),
  setRepositoryPinned: (request) => invoke('repository:setPinned', request),
  refreshRepository: (repoPath) => invoke('repository:refresh', repoPath),
  getDiff: (request) => invoke('repository:diff', request),
  getHistory: (repoPath) => invoke('repository:history', repoPath),
  getCommitDetails: (request) => invoke('repository:commitDetails', request),
  getCommitFileDiff: (request) => invoke('repository:commitFileDiff', request),
  getProjectMemory: (repoPath) => invoke('repository:projectMemory', repoPath),
  getProjectWiki: (repoPath) => invoke('repository:projectWiki', repoPath),
  scanProjectMemory: (repoPath) => invoke('repository:scanProjectMemory', repoPath),
  generateProjectWiki: (repoPath) => invoke('repository:generateProjectWiki', repoPath),
  getProjectMemoryMcpConfig: (repoPath) => invoke('repository:projectMemoryMcpConfig', repoPath),
  getAssistantPolicy: (repoPath) => invoke('assistants:getPolicy', repoPath),
  setAssistantPolicy: (update) => invoke('assistants:setPolicy', update),
  getActivityLog: (query) => invoke('activity:list', query),
  clearActivityLog: (repoPath, confirmed) => invoke('activity:clear', repoPath, confirmed),
  generateDailyReview: (request) => invoke('daily:generate', request),
  getGitConfig: (repoPath) => invoke('repository:gitConfig', repoPath),
  setLocalGitIdentity: (request) => invoke('repository:setLocalGitIdentity', request),
  stageFile: (request) => invoke('git:stageFile', request),
  unstageFile: (request) => invoke('git:unstageFile', request),
  stageHunk: (request) => invoke('git:stageHunk', request),
  unstageHunk: (request) => invoke('git:unstageHunk', request),
  stageAll: (repoPath) => invoke('git:stageAll', repoPath),
  unstageAll: (repoPath) => invoke('git:unstageAll', repoPath),
  discardFile: (request) => invoke('git:discardFile', request),
  deleteUntrackedFile: (request) => invoke('git:deleteUntrackedFile', request),
  commit: (request) => invoke('git:commit', request),
  listStashes: (repoPath) => invoke('stash:list', repoPath),
  createStash: (request) => invoke('stash:create', request),
  applyStash: (request) => invoke('stash:apply', request),
  dropStash: (request) => invoke('stash:drop', request),
  fetch: (repoPath) => invoke('git:fetch', repoPath),
  pull: (repoPath) => invoke('git:pull', repoPath),
  push: (repoPath) => invoke('git:push', repoPath),
  publishBranch: (request) => invoke('git:publishBranch', request),
  createBranch: (request) => invoke('git:createBranch', request),
  updateBranchDescription: (request) => invoke('git:updateBranchDescription', request),
  switchBranch: (request) => invoke('git:switchBranch', request),
  deleteBranch: (request) => invoke('git:deleteBranch', request),
  acceptOurs: (request) => invoke('merge:acceptOurs', request),
  acceptTheirs: (request) => invoke('merge:acceptTheirs', request),
  markResolved: (request) => invoke('merge:markResolved', request),
  mergeBranch: (request) => invoke('merge:start', request),
  continueMergeOperation: (repoPath) => invoke('merge:continue', repoPath),
  abortMergeOperation: (repoPath) => invoke('merge:abort', repoPath),
  openInEditor: (request) => invoke('editor:open', request),
  openTerminal: (targetPath) => invoke('terminal:open', targetPath),
  listProviders: () => invoke('providers:list'),
  listAssistants: () => invoke('assistants:list'),
  checkAssistants: () => invoke('assistants:check'),
  generateCommitMessage: (request) => invoke('assistants:generateCommitMessage', request),
  generateBranchDraft: (request) => invoke('assistants:generateBranchDraft', request),
  generateBranchDescription: (request) => invoke('assistants:generateBranchDescription', request),
  getGitHubCliStatus: (repoPath) => invoke('providers:githubCliStatus', repoPath),
  generatePullRequestText: (request) => invoke('assistants:generatePullRequestText', request),
  createGitHubPullRequest: (request) => invoke('providers:createGitHubPullRequest', request),
  getCurrentBranchPullRequest: (repoPath) => invoke('providers:currentGitHubPullRequest', repoPath),
  listGitHubPullRequests: (repoPath) => invoke('providers:listGitHubPullRequests', repoPath),
  getGitHubPullRequestDetails: (request) => invoke('providers:getGitHubPullRequestDetails', request),
  getGitHubPullRequestChecks: (request) => invoke('providers:getGitHubPullRequestChecks', request),
  getGitHubPullRequestDiff: (request) => invoke('providers:getGitHubPullRequestDiff', request),
  checkoutGitHubPullRequest: (request) => invoke('providers:checkoutGitHubPullRequest', request),
  generateReviewReport: (request) => invoke('assistants:generateReviewReport', request)
}

contextBridge.exposeInMainWorld('branchPilot', branchPilot)
